#+TITLE Emacs Configuration

- [[https://www.youtube.com/watch?v=VIuOwIBL-ZUp][Emacs Tutorial - Overview of Init Files Using Org-Mode and Use-Package (Part 1 of 2)]]
- [[https://www.youtube.com/watch?v=gRb3bq0NiXY][Emacs Tutorial - Init.el setup for an org-mode config (Part 2 of 2)]]

* SBCL/Slime/Quicklisp 

  #+BEGIN_SRC emacs-lisp
    (load (expand-file-name "~/quicklisp/slime-helper.el"))
    (setq inferior-lisp-program "sbcl")
  #+END_SRC

** Rainbow Delimiters

   #+BEGIN_SRC emacs-lisp
     (use-package rainbow-delimiters
       :ensure t
       :config
       ;; Enables rainbow-delimiters-mode in Emacs Lisp buffers
       (add-hook 'emacs-lisp-mode-hook 'rainbow-delimiters-mode)

       ;; Enables rainbow-delimiters-mode in Clojure buffers.
       (add-hook 'clojure-mode-hook 'rainbow-delimiters-mode)

       ;; enables rainbow-delimiters-mode in other Lisp mode buffers.
       (add-hook 'lisp-mode-hook 'rainbow-delimiters-mode)
       )
   #+END_SRC

* Evil Mode

  Evil is an extensible vi layer for Emacs. It emulates the main
  features of Vim, and provides facilities for writing custom
  extensions. Also see our page on [[http://emacswiki.org/emacs/Evil][EmacsWiki]].

  #+BEGIN_SRC emacs-lisp
    (use-package evil
      :ensure t
      :config
      (evil-mode 1)
      )
    ;;(use-package org-evil
    ;;  :ensure t
    ;;  :config
    ;;  (add-to-list 'auto-mode-alist '("\\.org$" . org-mode))
    ;;  )
    ;;
    ;;(use-package evil-leader
    ;;  :ensure t
    ;;  :config
    ;;  (global-evil-leader-mode)
    ;;  (evil-leader/set-leader ","))
    ;;
    ;;(use-package evil-surround
    ;;  :ensure t
    ;;  :config
    ;;  (global-evil-surround-mode))
  #+END_SRC
  
* Org Mode

  Org mode is for keeping notes, maintaining TODO lists, planning
  projects, and authoring documents with a fast and effective
  plain-text system.
  - http://orgmode.org/

  #+BEGIN_SRC emacs-lisp
    (setq org-src-fontify-natively t) 
  #+END_SRC

* Helm

  Helm is an Emacs framework for incremental completions and narrowing
  selections. It helps to rapidly complete file names, buffer names, or
  any other Emacs interactions requiring selecting an item from a list
  of possible choices.
  - [[https://github.com/emacs-helm/helm]]
    
  #+BEGIN_SRC emacs-lisp
    (use-package helm
      :ensure t
      :config
      )
  #+END_SRC
  
* Powerline

  #+BEGIN_SRC emacs-lisp
    (use-package powerline
      :ensure t
      :config
      (powerline-default-theme)
      )
  #+END_SRC
  
* Temp
#+BEGIN_SRC emacs-lisp
(add-to-list 'auto-mode-alist '("\\.ledger$" . ledger-mode))
#+END_SRC
